{"uuid": "08eb7bb7-fbf8-40f8-a384-cc16d26d155d", "children": ["2db6d199-d517-4472-bba1-599e69171134"], "befores": [{"name": "set_up", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_101.0.4951 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024711F83DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\טק קריירה\\PycharmProjects\\AUTOMATIC-TESTING\\Tests\\Base\\base.py\", line 9, in set_up\n    self.driver = webdriver.Chrome(ChromeDriverManager().install())\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\chrome.py\", line 38, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 27, in _get_driver_path\n    binary_path = self.driver_cache.find_driver(driver)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 87, in find_driver\n    driver_version = driver.get_version()\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 40, in get_version\n    self.get_latest_release_version()\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\drivers\\chrome.py\", line 39, in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\core\\http.py\", line 32, in get\n    resp = requests.get(url=url, verify=self._ssl_verify, **kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\טק קריירה\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1653435477615, "stop": 1653459017791}], "start": 1653435477615, "stop": 1653459023860}